// <auto-generated />
using JhonnyHomeStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JhonnyHomeStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JhonnyHomeStudioDbContext))]
    [Migration("20260714120000_RemoveServiceAndProductCategoriesAndServiceDuration")]
    partial class RemoveServiceAndProductCategoriesAndServiceDuration
    {
    }
}
