// <auto-generated />
using System;
using JhonnyHomeStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhonnyHomeStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JhonnyHomeStudioDbContext))]
    partial class JhonnyHomeStudioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Address", b =>
                {
                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Complement")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReferencePoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.AdminUser", b =>
                {
                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ServicePriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.AppointmentStatusHistory", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("AppointmentStatusHistory");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId2")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId3")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Service", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId2")
                        .HasColumnType("uuid");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceCategory");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Story", b =>
                {
                    b.Property<string>("ActionButtonText")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ActionValue")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("CreatedByAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.StoryView", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("StoryId", "CustomerId")
                        .IsUnique();

                    b.ToTable("StoryView");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TempId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId2")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TempId3")
                        .HasColumnType("uuid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Address", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("JhonnyHomeStudio.Domain.Entities.AdminUser", "UserId")
                        .HasPrincipalKey("JhonnyHomeStudio.Domain.Entities.User", "TempId2")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("TempId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.AppointmentStatusHistory", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Appointment", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AppointmentId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JhonnyHomeStudio.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .HasPrincipalKey("TempId3")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Customer", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("JhonnyHomeStudio.Domain.Entities.Customer", "UserId")
                        .HasPrincipalKey("JhonnyHomeStudio.Domain.Entities.User", "TempId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Service", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Story", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.AdminUser", "CreatedByAdminUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminUserId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Service", "Service")
                        .WithMany("Stories")
                        .HasForeignKey("ServiceId")
                        .HasPrincipalKey("TempId2")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAdminUser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.StoryView", b =>
                {
                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Customer", "Customer")
                        .WithMany("StoryViews")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("TempId3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JhonnyHomeStudio.Domain.Entities.Story", "Story")
                        .WithMany("Views")
                        .HasForeignKey("StoryId")
                        .HasPrincipalKey("TempId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Appointments");

                    b.Navigation("StoryViews");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("JhonnyHomeStudio.Domain.Entities.Story", b =>
                {
                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
